spring.application.name=aplikacja_wspomagajaca_cwiczenia
spring.datasource.url=jdbc:mysql://localhost:3306/rehab_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
